export const LIVESTREAMS = [
  {
    id: 'ls_01',
    title: 'Živý výprodej — MaxiGreens jaro 2026',
    streamer: {
      id: 'user_mg',
      name: 'MaxiGreens',
      avatar: null,
      verified: true,
      followers: 48200,
    },
    status: 'live',
    viewers: 1340,
    category: 'Jídlo',
    tags: ['slevy', 'čerstvé', 'bio'],
    startedAt: '2026-09-20T18:30:00Z',
    duration: 2700,
    thumbnailUrl: 'https://via.placeholder.com/400x700/2A2118/C8842D?text=LIVE',
    chatEnabled: true,
    deals: [
      { id: 'ld_01', title: 'Bio Matcha Tea 100g', originalPrice: 899, salePrice: 399, discount: 56 },
      { id: 'ld_02', title: 'Organic Spirulina 500g', originalPrice: 649, salePrice: 299, discount: 54 },
    ],
  },
  {
    id: 'ls_02',
    title: 'Kosmetika — live swatch & review',
    streamer: {
      id: 'user_klara',
      name: 'Klára Beauty',
      avatar: null,
      verified: false,
      followers: 12800,
    },
    status: 'live',
    viewers: 423,
    category: 'Krása',
    tags: ['makeup', 'swatches', 'tutorial'],
    startedAt: '2026-09-20T19:00:00Z',
    duration: 1800,
    thumbnailUrl: 'https://via.placeholder.com/400x700/3D3028/E91E63?text=LIVE',
    chatEnabled: true,
    deals: [
      { id: 'ld_03', title: 'Sada rtěnek 5 ks', originalPrice: 1299, salePrice: 599, discount: 54 },
    ],
  },
  {
    id: 'ls_03',
    title: 'Elektronika — novinky a flash deals',
    streamer: {
      id: 'user_tech',
      name: 'TechDeals CZ',
      avatar: null,
      verified: true,
      followers: 67300,
    },
    status: 'live',
    viewers: 3120,
    category: 'Elektronika',
    tags: ['flash deal', 'tech', 'gadgety'],
    startedAt: '2026-09-20T17:45:00Z',
    duration: 5100,
    thumbnailUrl: 'https://via.placeholder.com/400x700/1A1410/2196F3?text=LIVE',
    chatEnabled: true,
    deals: [
      { id: 'ld_04', title: 'Bezdrátová sluchátka Pro', originalPrice: 2499, salePrice: 999, discount: 60 },
      { id: 'ld_05', title: 'Power bank 20000mAh', originalPrice: 899, salePrice: 449, discount: 50 },
      { id: 'ld_06', title: 'Smart hodinky Lite', originalPrice: 1999, salePrice: 799, discount: 60 },
    ],
  },
  {
    id: 'ls_04',
    title: 'Móda — podzimní kolekce 2026',
    streamer: {
      id: 'user_moda',
      name: 'StyleHunter',
      avatar: null,
      verified: false,
      followers: 23100,
    },
    status: 'live',
    viewers: 876,
    category: 'Móda',
    tags: ['móda', 'podzim', 'lookbook'],
    startedAt: '2026-09-20T18:00:00Z',
    duration: 3600,
    thumbnailUrl: 'https://via.placeholder.com/400x700/2A2118/9C27B0?text=LIVE',
    chatEnabled: true,
    deals: [
      { id: 'ld_07', title: 'Kožená bunda — limited', originalPrice: 5999, salePrice: 2499, discount: 58 },
    ],
  },
  {
    id: 'ls_05',
    title: 'Sport & outdoor — vybavení na sezónu',
    streamer: {
      id: 'user_sport',
      name: 'OutdoorMaster',
      avatar: null,
      verified: true,
      followers: 31500,
    },
    status: 'upcoming',
    viewers: 0,
    category: 'Sport',
    tags: ['outdoor', 'turistika', 'vybavení'],
    startsAt: '2026-09-20T20:00:00Z',
    thumbnailUrl: 'https://via.placeholder.com/400x700/1A1410/FF9800?text=SOON',
    chatEnabled: false,
    deals: [],
  },
];
