export const DEALS = [
  {
    id: '1',
    type: 'deal',
    brand: 'Tomáš Novák',
    handle: '@tomasdance',
    avatar: 'https://images.pexels.com/photos/8928721/pexels-photo-8928721.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Nike Air Max -40% v Praze',
    description: 'Praha by night hits different 🔥 #praha #nike #czech',
    tags: ['praha', 'nike', 'czech', 'deal'],
    song: 'Original Sound - DJ CzechBeats',
    discount: '40%',
    originalPrice: '2999 Kč',
    salePrice: '1799 Kč',
    image: 'https://images.pexels.com/photos/32037696/pexels-photo-32037696.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '128.4K',
    comments: '2,341',
    shares: '5,672',
    saves: '12.1K',
    timeAgo: '2h',
    verified: true,
    category: 'Móda',
    location: 'Praha',
    country: 'CZ',
  },
  {
    id: 'ad_1',
    type: 'ad',
    brand: 'Booking.com',
    handle: '@booking_eu',
    avatar: 'https://images.pexels.com/photos/24357593/pexels-photo-24357593.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Last minute dovolená od 4990 Kč',
    description: 'Ušetřete až 60% na letní dovolenou. Rezervujte teď! 🏖️',
    tags: ['dovolena', 'travel', 'booking', 'sleva'],
    song: 'Summer Vibes - Holiday Mix',
    discount: '60%',
    originalPrice: '12990 Kč',
    salePrice: '4990 Kč',
    image: 'https://images.pexels.com/photos/24357593/pexels-photo-24357593.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '89.2K',
    comments: '1,892',
    shares: '3,210',
    saves: '45.6K',
    timeAgo: 'Sponzorované',
    verified: true,
    category: 'Cestování',
    location: 'Evropa',
    country: 'EU',
    cta: 'Rezervovat',
    ctaUrl: 'https://booking.com',
    advertiser: 'Booking.com',
    impressionId: 'imp_001',
  },
  {
    id: '2',
    type: 'deal',
    brand: 'Eva Svobodová',
    handle: '@evacooks',
    avatar: 'https://images.pexels.com/photos/24357593/pexels-photo-24357593.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Zoot kupón -30% na módu',
    description: 'Svíčková na smetaně recipe 🇨🇿 Traditional Czech food!',
    tags: ['svickova', 'czechfood', 'recipe', 'cooking'],
    song: 'Kitchen Vibes - Lo-Fi Beats',
    discount: '30%',
    originalPrice: '1500 Kč',
    salePrice: '1050 Kč',
    image: 'https://images.pexels.com/photos/24357593/pexels-photo-24357593.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '89.2K',
    comments: '1,892',
    shares: '3,210',
    saves: '45.6K',
    timeAgo: '5h',
    verified: true,
    category: 'Móda',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: '3',
    type: 'deal',
    brand: 'Jan Dvořák',
    handle: '@janhikes',
    avatar: 'https://images.pexels.com/photos/8659357/pexels-photo-8659357.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Alza iPhone 16 Pro za skvělou cenu',
    description: 'Hiking in České Švýcarsko 🏔️ Best views in Czechia!',
    tags: ['hiking', 'ceskesvycarsko', 'nature', 'czechia'],
    song: 'Mountain Air - Ambient Sounds',
    discount: '15%',
    originalPrice: '34990 Kč',
    salePrice: '29741 Kč',
    image: 'https://images.pexels.com/photos/8659357/pexels-photo-8659357.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '256.7K',
    comments: '4,567',
    shares: '8,901',
    saves: '67.3K',
    timeAgo: '1h',
    verified: true,
    category: 'Elektronika',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: 'ad_2',
    type: 'ad',
    brand: 'Wolt',
    handle: '@wolt_eu',
    avatar: 'https://images.pexels.com/photos/29609216/pexels-photo-29609216.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'První objednávka zdarma',
    description: 'Objednejte si jídlo poprvé a dostanete slevu 200 Kč 🍕',
    tags: ['jidlo', 'wolt', 'doprava', 'praha'],
    song: 'Food Delivery Beat - Urban Sounds',
    discount: '200 Kč',
    originalPrice: '',
    salePrice: 'Zdarma',
    image: 'https://images.pexels.com/photos/29609216/pexels-photo-29609216.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '432.1K',
    comments: '12,345',
    shares: '23,456',
    saves: '89.2K',
    timeAgo: 'Sponzorované',
    verified: true,
    category: 'Jídlo',
    location: 'Praha',
    country: 'CZ',
    cta: 'Objednat',
    ctaUrl: 'https://wolt.com',
    advertiser: 'Wolt',
    impressionId: 'imp_002',
  },
  {
    id: '4',
    type: 'deal',
    brand: 'Lucie Černá',
    handle: '@luciedogs',
    avatar: 'https://images.pexels.com/photos/29609216/pexels-photo-29609216.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Electroworld PS5 Slim v akci',
    description: 'My puppies fighting over a toy 😂 #dogs #puppies #czech',
    tags: ['dogs', 'puppies', 'funny', 'czech'],
    song: 'Funny Pet Moments - Sound Collection',
    discount: '20%',
    originalPrice: '14999 Kč',
    salePrice: '11999 Kč',
    image: 'https://images.pexels.com/photos/29609216/pexels-photo-29609216.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '432.1K',
    comments: '12,345',
    shares: '23,456',
    saves: '89.2K',
    timeAgo: '30m',
    verified: true,
    category: 'Elektronika',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: '5',
    type: 'deal',
    brand: 'Petra Procházková',
    handle: '@petrafashion',
    avatar: 'https://images.pexels.com/photos/1377452/pexels-photo-1377452.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Bata boty na léto od 599 Kč',
    description: 'Autumn street style in Praha 🍂 #fashion #prague #streetstyle',
    tags: ['fashion', 'prague', 'streetstyle', 'autumn'],
    song: 'Runway Walk - Fashion Beats',
    discount: '50%',
    originalPrice: '1199 Kč',
    salePrice: '599 Kč',
    image: 'https://images.pexels.com/photos/1377452/pexels-photo-1377452.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '178.9K',
    comments: '3,456',
    shares: '7,890',
    saves: '34.5K',
    timeAgo: '8h',
    verified: false,
    category: 'Obuv',
    location: 'Brno',
    country: 'CZ',
  },
  {
    id: 'ad_3',
    type: 'ad',
    brand: 'Slevomat',
    handle: '@slevomat_eu',
    avatar: 'https://images.pexels.com/photos/8904828/pexels-photo-8904828.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Wellness den za 499 Kč',
    description: 'Prague Old Town at golden hour 🌅 This city never gets old',
    tags: ['prague', 'oldtontown', 'travel', 'goldenhour'],
    song: 'City Lights - Ambient Loops',
    discount: '70%',
    originalPrice: '1699 Kč',
    salePrice: '499 Kč',
    image: 'https://images.pexels.com/photos/8904828/pexels-photo-8904828.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '521.3K',
    comments: '8,902',
    shares: '34,567',
    saves: '102.4K',
    timeAgo: 'Sponzorované',
    verified: true,
    category: 'Wellness',
    location: 'Praha',
    country: 'CZ',
    cta: 'Koupit',
    ctaUrl: 'https://slevomat.cz',
    advertiser: 'Slevomat',
    impressionId: 'imp_003',
  },
  {
    id: '6',
    type: 'deal',
    brand: 'Ondřej Král',
    handle: '@ondrejskates',
    avatar: 'https://images.pexels.com/photos/9409324/pexels-photo-9409324.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Mall.cz kávovar DeLonghi -35%',
    description: 'New trick unlocked at Stalin Plaza 🛹 #skate #prague #street',
    tags: ['skate', 'prague', 'street', 'trick'],
    song: 'Skate Punk Anthem - CzechRawk',
    discount: '35%',
    originalPrice: '18999 Kč',
    salePrice: '12349 Kč',
    image: 'https://images.pexels.com/photos/9409324/pexels-photo-9409324.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '312.8K',
    comments: '5,120',
    shares: '12,300',
    saves: '56.7K',
    timeAgo: '3h',
    verified: true,
    category: 'Domácnost',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: '7',
    type: 'deal',
    brand: 'Klára Müller',
    handle: '@klaraexplores',
    avatar: 'https://images.pexels.com/photos/8904828/pexels-photo-8904828.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'About You letní výprodej -60%',
    description: 'Prague Old Town at golden hour 🌅 This city never gets old',
    tags: ['prague', 'oldtontown', 'travel', 'goldenhour'],
    song: 'City Lights - Ambient Loops',
    discount: '60%',
    originalPrice: '2500 Kč',
    salePrice: '1000 Kč',
    image: 'https://images.pexels.com/photos/8904828/pexels-photo-8904828.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '521.3K',
    comments: '8,902',
    shares: '34,567',
    saves: '102.4K',
    timeAgo: '6h',
    verified: true,
    category: 'Móda',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: '8',
    type: 'deal',
    brand: 'Martin Horák',
    handle: '@martinfit',
    avatar: 'https://images.pexels.com/photos/8928721/pexels-photo-8928721.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'GymBeam protein -25% jen dnes',
    description: 'Post workout pump 💪 Čerstvý protein po tréninku #gym #fitness #czech',
    tags: ['gym', 'fitness', 'protein', 'workout'],
    song: 'Gym Mode - Heavy Beats',
    discount: '25%',
    originalPrice: '899 Kč',
    salePrice: '674 Kč',
    image: 'https://images.pexels.com/photos/8928721/pexels-photo-8928721.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '67.8K',
    comments: '1,234',
    shares: '3,456',
    saves: '8.9K',
    timeAgo: '45m',
    verified: true,
    category: 'Fitness',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: '9',
    type: 'deal',
    brand: 'Tereza Veselá',
    handle: '@terezalives',
    avatar: 'https://images.pexels.com/photos/1377452/pexels-photo-1377452.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Fotolab tisk fotek -40%',
    description: 'Vánoční fotky z dovolené 📸 Tiskni nejlepší momenty #foto #vanoce',
    tags: ['foto', 'print', 'vanoce', 'dovolena'],
    song: 'Memory Lane - Acoustic',
    discount: '40%',
    originalPrice: '599 Kč',
    salePrice: '359 Kč',
    image: 'https://images.pexels.com/photos/1377452/pexels-photo-1377452.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '45.2K',
    comments: '892',
    shares: '2,100',
    saves: '6.7K',
    timeAgo: '3h',
    verified: false,
    category: 'Služby',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: '10',
    type: 'deal',
    brand: 'Jakub Svoboda',
    handle: '@jakubtech',
    avatar: 'https://images.pexels.com/photos/8659357/pexels-photo-8659357.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Samsung Galaxy S24 Ultra -30%',
    description: 'Nejlepší mobil roku 📱 AI funkce jsou bomba #samsung #tech #ai',
    tags: ['samsung', 'galaxy', 'ai', 'tech'],
    song: 'Tech Life - Synthwave',
    discount: '30%',
    originalPrice: '32990 Kč',
    salePrice: '23093 Kč',
    image: 'https://images.pexels.com/photos/8659357/pexels-photo-8659357.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '198.5K',
    comments: '3,456',
    shares: '7,890',
    saves: '45.6K',
    timeAgo: '1h',
    verified: true,
    category: 'Elektronika',
    location: 'Online',
    country: 'CZ',
  },
  {
    id: 'ad_4',
    type: 'ad',
    brand: 'Alza',
    handle: '@alza_eu',
    avatar: 'https://images.pexels.com/photos/9409324/pexels-photo-9409324.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'AlzaBlack Friday - až -70%',
    description: 'Největší slevy roku! 🖤 Všechny kategorie #alzablack #slevy',
    tags: ['alzablack', 'blackfriday', 'slevy', 'nakup'],
    song: 'Black Friday - Bass Drops',
    discount: '70%',
    originalPrice: '9999 Kč',
    salePrice: '2999 Kč',
    image: 'https://images.pexels.com/photos/9409324/pexels-photo-9409324.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '892.1K',
    comments: '15,678',
    shares: '45,678',
    saves: '234.5K',
    timeAgo: 'Sponzorované',
    verified: true,
    category: 'Elektronika',
    location: 'Online',
    country: 'EU',
    cta: 'Nakoupit',
    ctaUrl: 'https://alza.cz',
    advertiser: 'Alza',
    impressionId: 'imp_004',
  },
  {
    id: '11',
    type: 'deal',
    brand: 'Anna Kratochvílová',
    handle: '@annacooks',
    avatar: 'https://images.pexels.com/photos/24357593/pexels-photo-24357593.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Rohlík sleva -20% na první nákup',
    description: 'Čerstvé potraviny až ke dveřím 🥖 #jídlo #rohlík #domů',
    tags: ['jidlo', 'rohlík', 'doprava', 'cas'],
    song: 'Kitchen Vibes - Lo-Fi Beats',
    discount: '20%',
    originalPrice: '500 Kč',
    salePrice: '400 Kč',
    image: 'https://images.pexels.com/photos/24357593/pexels-photo-24357593.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '34.5K',
    comments: '678',
    shares: '1,234',
    saves: '5.6K',
    timeAgo: '2h',
    verified: true,
    category: 'Jídlo',
    location: 'Praha',
    country: 'CZ',
  },
  {
    id: '12',
    type: 'deal',
    brand: 'Pavel Novotný',
    handle: '@pavelruns',
    avatar: 'https://images.pexels.com/photos/8659357/pexels-photo-8659357.jpeg?auto=compress&cs=tinysrgb&h=120&w=120',
    title: 'Nike běžecké boty -35%',
    description: 'Ranní běh v Riegrových sadech 🏃‍♂️ Best morning ever #running #prague',
    tags: ['running', 'nike', 'prague', 'morning'],
    song: 'Running Beat - High Energy',
    discount: '35%',
    originalPrice: '2499 Kč',
    salePrice: '1624 Kč',
    image: 'https://images.pexels.com/photos/8659357/pexels-photo-8659357.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    likes: '89.3K',
    comments: '1,567',
    shares: '4,321',
    saves: '12.3K',
    timeAgo: '4h',
    verified: true,
    category: 'Obuv',
    location: 'Praha',
    country: 'CZ',
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Vše', icon: '🔥' },
  { id: 'fashion', name: 'Móda', icon: '👗' },
  { id: 'electronics', name: 'Elektronika', icon: '📱' },
  { id: 'food', name: 'Jídlo', icon: '🍔' },
  { id: 'travel', name: 'Cestování', icon: '✈️' },
  { id: 'home', name: 'Domácnost', icon: '🏠' },
  { id: 'wellness', name: 'Wellness', icon: '💆' },
  { id: 'shoes', name: 'Obuv', icon: '👟' },
];

export const EUROPEAN_COUNTRIES = [
  { id: 'CZ', name: 'Česko', flag: '🇨🇿' },
  { id: 'SK', name: 'Slovensko', flag: '🇸🇰' },
  { id: 'PL', name: 'Polsko', flag: '🇵🇱' },
  { id: 'DE', name: 'Německo', flag: '🇩🇪' },
  { id: 'AT', name: 'Rakousko', flag: '🇦🇹' },
  { id: 'HU', name: 'Maďarsko', flag: '🇭🇺' },
];

export const CUSTOMIZATION_PRESETS = {
  minimal: {
    name: 'Minimální',
    description: 'Čistý a jednoduchý vzhled',
    cardStyle: 'flat',
    showDiscount: true,
    showOriginalPrice: true,
    showTags: false,
    showSong: false,
    gradientOpacity: 0.4,
  },
  standard: {
    name: 'Standardní',
    description: 'Klasický vzhled s detaily',
    cardStyle: 'elevated',
    showDiscount: true,
    showOriginalPrice: true,
    showTags: true,
    showSong: true,
    gradientOpacity: 0.6,
  },
  premium: {
    name: 'Prémiový',
    description: 'Bohatý vzhled s animacemi',
    cardStyle: 'glass',
    showDiscount: true,
    showOriginalPrice: true,
    showTags: true,
    showSong: true,
    gradientOpacity: 0.7,
  },
};
