export const USERS = [
  {
    id: 'u1',
    name: 'Petr Novák',
    handle: '@petr_novak',
    email: 'petr@lovedeal.cz',
    avatar: 'https://via.placeholder.com/200/FF6B35/FFF?text=PN',
    bio: 'Milovník slev a technologií. Hledám nejlepší dealy v Praze.',
    location: 'Praha',
    country: 'CZ',
    followers: 1234,
    following: 567,
    dealsPosted: 89,
    dealsSaved: 234,
    rating: 4.8,
    verified: true,
    joinedAt: '2026-01-15',
  },
  {
    id: 'u2',
    name: 'Eva Svobodová',
    handle: '@eva_s',
    email: 'eva@lovedeal.cz',
    avatar: 'https://via.placeholder.com/200/E91E63/FFF?text=ES',
    bio: 'Móda a krása. Sdílím nejlepší nabídky z obchodů.',
    location: 'Brno',
    country: 'CZ',
    followers: 892,
    following: 345,
    dealsPosted: 56,
    dealsSaved: 178,
    rating: 4.6,
    verified: false,
    joinedAt: '2026-03-22',
  },
  {
    id: 'u3',
    name: 'Jan Procházka',
    handle: '@jan_pro',
    email: 'jan@lovedeal.cz',
    avatar: 'https://via.placeholder.com/200/2196F3/FFF?text=JP',
    bio: 'Elektronika a gaming. PlayStation, PC, mobilní telefony.',
    location: 'Ostrava',
    country: 'CZ',
    followers: 2345,
    following: 123,
    dealsPosted: 145,
    dealsSaved: 67,
    rating: 4.9,
    verified: true,
    joinedAt: '2025-11-08',
  },
  {
    id: 'u4',
    name: 'Marie Dvořáková',
    handle: '@marie_d',
    email: 'marie@lovedeal.cz',
    avatar: 'https://via.placeholder.com/200/4CAF50/FFF?text=MD',
    bio: 'Domácnost a vaření. Recepty a slevy na potraviny.',
    location: 'Plzeň',
    country: 'CZ',
    followers: 567,
    following: 890,
    dealsPosted: 34,
    dealsSaved: 456,
    rating: 4.3,
    verified: false,
    joinedAt: '2026-05-10',
  },
  {
    id: 'u5',
    name: 'Tomáš Horák',
    handle: '@tom_h',
    email: 'tomas@lovedeal.cz',
    avatar: 'https://via.placeholder.com/200/FF9800/FFF?text=TH',
    bio: 'Sport a outdoor. Běh, kolo, turistika. Vždy hledám vybavení za dobrou cenu.',
    location: 'Bratislava',
    country: 'SK',
    followers: 445,
    following: 234,
    dealsPosted: 28,
    dealsSaved: 123,
    rating: 4.5,
    verified: false,
    joinedAt: '2026-07-01',
  },
];
